CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age SMALLINT,
    grade CHAR(2),
    course VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    dob DATE,
    blood_group VARCHAR(5),
    country VARCHAR(50)
)

INSERT INTO
    students (
        first_name,
        last_name,
        age,
        grade,
        course,
        email,
        dob,
        blood_group,
        country
    )
VALUES (
        'John',
        'Doe',
        20,
        'A',
        'Computer Science',
        'john.doe1@example.com',
        '2005-01-15',
        'A+',
        'USA'
    ),
    (
        'Jane',
        'Smith',
        22,
        'B',
        'Mathematics',
        'jane.smith2@example.com',
        '2003-03-20',
        'O+',
        'UK'
    ),
    (
        'Michael',
        'Brown',
        19,
        'A',
        'Physics',
        'michael.brown3@example.com',
        '2006-07-11',
        'B+',
        'Canada'
    ),
    (
        'Emily',
        'Davis',
        21,
        'A',
        'Biology',
        'emily.davis4@example.com',
        '2004-02-25',
        'AB+',
        'Australia'
    ),
    (
        'Daniel',
        'Wilson',
        23,
        'C',
        'Chemistry',
        'daniel.wilson5@example.com',
        '2002-08-30',
        'A-',
        'Germany'
    ),
    (
        'Sophia',
        'Taylor',
        20,
        'B',
        'Economics',
        'sophia.taylor6@example.com',
        '2005-05-10',
        'O-',
        'France'
    ),
    (
        'James',
        'Anderson',
        22,
        'A',
        'History',
        'james.anderson7@example.com',
        '2003-12-18',
        'B-',
        'Italy'
    ),
    (
        'Olivia',
        'Martinez',
        21,
        'B',
        'Political Science',
        'olivia.martinez8@example.com',
        '2004-04-22',
        'AB-',
        'Spain'
    ),
    (
        'William',
        'Thomas',
        19,
        'A',
        'Engineering',
        'william.thomas9@example.com',
        '2006-09-14',
        'A+',
        'Netherlands'
    ),
    (
        'Ava',
        'Harris',
        20,
        'C',
        'Philosophy',
        'ava.harris10@example.com',
        '2005-06-19',
        'O+',
        'Sweden'
    ),
    (
        'Ethan',
        'Clark',
        21,
        'B',
        'Computer Science',
        'ethan.clark11@example.com',
        '2004-01-29',
        'B+',
        'USA'
    ),
    (
        'Isabella',
        'Lewis',
        23,
        'A',
        'Mathematics',
        'isabella.lewis12@example.com',
        '2002-10-05',
        'AB+',
        'UK'
    ),
    (
        'Alexander',
        'Robinson',
        22,
        'B',
        'Physics',
        'alexander.robinson13@example.com',
        '2003-11-16',
        'A-',
        'Canada'
    ),
    (
        'Mia',
        'Walker',
        20,
        'A',
        'Biology',
        'mia.walker14@example.com',
        '2005-02-08',
        'O-',
        'Australia'
    ),
    (
        'Benjamin',
        'Hall',
        21,
        'C',
        'Chemistry',
        'benjamin.hall15@example.com',
        '2004-07-12',
        'B-',
        'Germany'
    ),
    (
        'Charlotte',
        'Allen',
        22,
        'A',
        'Economics',
        'charlotte.allen16@example.com',
        '2003-09-25',
        'AB-',
        'France'
    ),
    (
        'Lucas',
        'Young',
        19,
        'B',
        'History',
        'lucas.young17@example.com',
        '2006-03-21',
        'A+',
        'Italy'
    ),
    (
        'Amelia',
        'King',
        20,
        'A',
        'Political Science',
        'amelia.king18@example.com',
        '2005-12-09',
        'O+',
        'Spain'
    ),
    (
        'Henry',
        'Wright',
        23,
        'B',
        'Engineering',
        'henry.wright19@example.com',
        '2002-05-14',
        'B+',
        'Netherlands'
    ),
    (
        'Harper',
        'Scott',
        21,
        'C',
        'Philosophy',
        'harper.scott20@example.com',
        '2004-08-03',
        'AB+',
        'Sweden'
    ),
    (
        'Sebastian',
        'Green',
        20,
        'B',
        'Computer Science',
        'sebastian.green21@example.com',
        '2005-01-27',
        'A-',
        'USA'
    ),
    (
        'Evelyn',
        'Adams',
        22,
        'A',
        'Mathematics',
        'evelyn.adams22@example.com',
        '2003-06-18',
        'O-',
        'UK'
    ),
    (
        'Jack',
        'Baker',
        21,
        'C',
        'Physics',
        'jack.baker23@example.com',
        '2004-04-30',
        'B-',
        'Canada'
    ),
    (
        'Abigail',
        'Nelson',
        19,
        'A',
        'Biology',
        'abigail.nelson24@example.com',
        '2006-11-12',
        'AB-',
        'Australia'
    ),
    (
        'Samuel',
        'Carter',
        23,
        'B',
        'Chemistry',
        'samuel.carter25@example.com',
        '2002-02-28',
        'A+',
        'Germany'
    ),
    (
        'Ella',
        'Mitchell',
        20,
        'A',
        'Economics',
        'ella.mitchell26@example.com',
        '2005-09-19',
        'O+',
        'France'
    ),
    (
        'David',
        'Perez',
        21,
        'C',
        'History',
        'david.perez27@example.com',
        '2004-07-23',
        'B+',
        'Italy'
    ),
    (
        'Sofia',
        'Roberts',
        22,
        'B',
        'Political Science',
        'sofia.roberts28@example.com',
        '2003-03-02',
        'AB+',
        'Spain'
    ),
    (
        'Joseph',
        'Turner',
        19,
        'A',
        'Engineering',
        'joseph.turner29@example.com',
        '2006-10-07',
        'A-',
        'Netherlands'
    ),
    (
        'Grace',
        'Phillips',
        20,
        'C',
        'Philosophy',
        'grace.phillips30@example.com',
        '2005-12-15',
        'O-',
        'Sweden'
    ),
    (
        'Matthew',
        'Campbell',
        21,
        'B',
        'Computer Science',
        'matthew.campbell31@example.com',
        '2004-05-11',
        'B-',
        'USA'
    ),
    (
        'Chloe',
        'Parker',
        23,
        'A',
        'Mathematics',
        'chloe.parker32@example.com',
        '2002-07-06',
        'AB-',
        'UK'
    ),
    (
        'Anthony',
        'Evans',
        20,
        'C',
        'Physics',
        'anthony.evans33@example.com',
        '2005-03-27',
        'A+',
        'Canada'
    ),
    (
        'Victoria',
        'Edwards',
        22,
        'B',
        'Biology',
        'victoria.edwards34@example.com',
        '2003-09-08',
        'O+',
        'Australia'
    ),
    (
        'Andrew',
        'Collins',
        21,
        'A',
        'Chemistry',
        'andrew.collins35@example.com',
        '2004-11-03',
        'B+',
        'Germany'
    ),
    (
        'Scarlett',
        'Stewart',
        19,
        'B',
        'Economics',
        'scarlett.stewart36@example.com',
        '2006-01-20',
        'AB+',
        'France'
    ),
    (
        'Joshua',
        'Morris',
        20,
        'C',
        'History',
        'joshua.morris37@example.com',
        '2005-06-14',
        'A-',
        'Italy'
    ),
    (
        'Aria',
        'Rogers',
        22,
        'A',
        'Political Science',
        'aria.rogers38@example.com',
        '2003-12-29',
        'O-',
        'Spain'
    ),
    (
        'Christopher',
        'Reed',
        23,
        'B',
        'Engineering',
        'christopher.reed39@example.com',
        '2002-08-22',
        'B-',
        'Netherlands'
    ),
    (
        'Lily',
        'Cook',
        21,
        'C',
        'Philosophy',
        'lily.cook40@example.com',
        '2004-10-13',
        'AB-',
        'Sweden'
    ),
    (
        'Jackson',
        'Morgan',
        20,
        'A',
        'Computer Science',
        'jackson.morgan41@example.com',
        '2005-02-05',
        'A+',
        'USA'
    ),
    (
        'Zoe',
        'Bell',
        22,
        'B',
        'Mathematics',
        'zoe.bell42@example.com',
        '2003-11-19',
        'O+',
        'UK'
    ),
    (
        'Gabriel',
        'Murphy',
        21,
        'C',
        'Physics',
        'gabriel.murphy43@example.com',
        '2004-03-01',
        'B+',
        'Canada'
    ),
    (
        'Hannah',
        'Bailey',
        19,
        'A',
        'Biology',
        'hannah.bailey44@example.com',
        '2006-04-09',
        'AB+',
        'Australia'
    ),
    (
        'Carter',
        'Rivera',
        23,
        'B',
        'Chemistry',
        'carter.rivera45@example.com',
        '2002-12-25',
        'A-',
        'Germany'
    ),
    (
        'Layla',
        'Cooper',
        20,
        'A',
        'Economics',
        'layla.cooper46@example.com',
        '2005-07-17',
        'O-',
        'France'
    ),
    (
        'Owen',
        'Richardson',
        22,
        'B',
        'History',
        'owen.richardson47@example.com',
        '2003-01-12',
        'B-',
        'Italy'
    ),
    (
        'Avery',
        'Howard',
        21,
        'C',
        'Political Science',
        'avery.howard48@example.com',
        '2004-09-27',
        'AB-',
        'Spain'
    ),
    (
        'Dylan',
        'Ward',
        19,
        'A',
        'Engineering',
        'dylan.ward49@example.com',
        '2006-06-16',
        'A+',
        'Netherlands'
    ),
    (
        'Sofia',
        'Peterson',
        20,
        'B',
        'Philosophy',
        'sofia.peterson50@example.com',
        '2005-05-21',
        'O+',
        'Sweden'
    );

SELECT * FROM students

SELECT first_name as "FN", age, grade FROM students

SELECT * FROM students ORDER BY age DESC

SELECT * FROM students ORDER BY first_name DESC